#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: About MyBetterWeb
url: 'https://peranakanfrancis.github.io/online-cv/'
description: MyBetterWeb is a managed by a solo frontend developer that is focused on building mobile optimized website with higher conversion rate. We are confident your website will work all the way up to the top.
baseurl: '' #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: berry # blue turquoise green berry orange ceramic
chrome_mobile_color: fa2a7b #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar
destination: _site

# Tracker
analytics: UA-129774437-2

social:
  name: peranakafrancis
  links:
    - https://twitter.com/peranakafrancis
    - https://www.facebook.com/mybetterweb.site/
    - https://www.linkedin.com/in/peranakafrancis
    - https://instagram.com/mybetterweb.site/
    - https://github.com/peranakafrancis
    - https://keybase.io/peranakafrancis
    - https://wa.link/pf0lud    
    - https://m.me/mybetterweb.site
twitter:
  username: peranakanfrancis
  card: summary

# jekyll gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

profile: true
livereload: true
time_zone: Asia/Kathmandu
source:
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter_opts:
      disable : true
highlighter: none
sass:
  sass_dir: _sass
  style: compressed
excludes: [ README.md, node_modules, Gemfile* ]

# Build settings
encoding: "utf-8"
compress_html:
  comments: [ "<!-- ", " -->" ]
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4001
host: 127.0.0.1
safe: false
